### ISSUE TITLE
nul1fs doesn't compile on Ubuntu 12

### ISSUE THREAD

**Issue by Genda1ph** [xrgtn/nullfs#5]
I've installed libfuse-dev, downloaded zip, extracted it and ran make nul1fs, result is below:
```
gendalph@namo:~/nullfs-master$ make nul1fs
cc   "-lfuse"  nul1fs.c   -o nul1fs
/tmp/ccKSs0Ur.o: In function `main':
nul1fs.c:(.text+0x4ae): undefined reference to `fuse_main_real'
collect2: ld returned 1 exit status
make: *** [nul1fs] Error 1
```
Workaround was to install pkg-config and compiling manually.
```
gcc -Wall -o nul1fs nul1fs.c $(pkg-config fuse --cflags --libs)
```
My workaround: adding these to Makefile
```
CFLAGS = -Wall `pkg-config fuse --cflags --libs`

nul1fs:
        gcc -o nul1fs nul1fs.c $(CFLAGS)
```

**Comment by Genda1ph** [comment]
And after altering Makefile, make complains about missing targets, so here's other two targets:
```
nullfs:
        g++ -o nullfs nullfs.c++ $(CFLAGS)

nulnfs:
        gcc -o nulnfs nulnfs.c $(CFLAGS)
```

**Comment by xrgtn** [comment]
Hello,

On Fri, Jan 22, 2016 at 03:31:18AM -0800, Genda1ph
wrote:
> And after altering Makefile, make complains
> about missing targets, so here's other
> two targets:

Sorry for insufficient Makefile, I've pushed a new
version right now and added a NOTE about
non-working nulnfs implementation.

On my stable Debian all targets build OK now,
please check on your system.

-- 
With best regards,
xrgtn

**Comment by xrgtn** [comment]
Hello,

On Fri, Jan 22, 2016 at 03:21:20AM -0800, Genda1ph
wrote:
> cc   "-lfuse"  nul1fsc   -o nul1fs
> /tmp/ccKSs0Uro: In function `main':
> nul1fsc:(text+0x4ae): undefined reference to `fuse_main_real'

This means that libfuse isn't installed in
standard /lib[/arch] or /usr/lib[/arch] path.
For example, on my Debian/stable:

xrgtn@ux280p:~/jff/nullfs$ dpkg -L libfuse-dev | grep \\.a
/usr/lib/i386-linux-gnu/libfuse.a
/usr/lib/i386-linux-gnu/libulockmgr.a
xrgtn@ux280p:~/jff/nullfs$ 

> Workaround was to install pkg-config and compiling manually
> gcc -Wall -o nul1fs nul1fsc $(pkg-config fuse --cflags --libs)
> 
> My workaround: adding these to Makefile
> CFLAGS = -Wall `pkg-config fuse --cflags --libs`
> 
> nul1fs:
>         gcc -o nul1fs nul1fsc $(CFLAGS)

I don't remember Ubuntu screwing up
libwhatever-dev packages before... Can you please
check what's wrong with their libfuse-dev package
and report a bug to them if anything's broken
there?

Here's a full libfuse-dev listing from Debian:

/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libfuse-dev
/usr/share/doc/libfuse-dev/changelog.Debian.gz
/usr/share/doc/libfuse-dev/changelog.gz
/usr/share/doc/libfuse-dev/examples
/usr/share/doc/libfuse-dev/examples/Makefile
/usr/share/doc/libfuse-dev/examples/fioc.h
/usr/share/doc/libfuse-dev/examples/null.c
/usr/share/doc/libfuse-dev/examples/hello_ll.c
/usr/share/doc/libfuse-dev/examples/hello.c
/usr/share/doc/libfuse-dev/examples/fusexmp_fh.c
/usr/share/doc/libfuse-dev/examples/fusexmp.c
/usr/share/doc/libfuse-dev/examples/fselclient.c
/usr/share/doc/libfuse-dev/examples/fsel.c
/usr/share/doc/libfuse-dev/examples/fioclient.c
/usr/share/doc/libfuse-dev/examples/fioc.c
/usr/share/doc/libfuse-dev/examples/cusexmp.c
/usr/share/doc/libfuse-dev/copyright
/usr/lib
/usr/lib/i386-linux-gnu
/usr/lib/i386-linux-gnu/libfuse.a
/usr/lib/i386-linux-gnu/libulockmgr.a
/usr/lib/i386-linux-gnu/pkgconfig
/usr/lib/i386-linux-gnu/pkgconfig/fuse.pc
/usr/include
/usr/include/ulockmgr.h
/usr/include/fuse.h
/usr/include/fuse
/usr/include/fuse/cuse_lowlevel.h
/usr/include/fuse/fuse_opt.h
/usr/include/fuse/fuse_lowlevel_compat.h
/usr/include/fuse/fuse_lowlevel.h
/usr/include/fuse/fuse_common_compat.h
/usr/include/fuse/fuse_common.h
/usr/include/fuse/fuse_compat.h
/usr/include/fuse/fuse.h
/usr/lib/i386-linux-gnu/libulockmgr.so
/usr/lib/i386-linux-gnu/libfuse.so

-- 
With best regards,
xrgtn

**Comment by Genda1ph** [comment]
Hello
Sorry for the late reply, I'll check it tomorrow.

**Comment by Genda1ph** [comment]
Updated Makefile doesn't work:
```
gendalph@namo:~/nullfs-master$ make all
cc   "-lfuse"  nul1fs.c   -o nul1fs
/tmp/ccT8jfGL.o: In function `main':
nul1fs.c:(.text+0x4ae): undefined reference to `fuse_main_real'
collect2: ld returned 1 exit status
make: *** [nul1fs] Error 1
```
Weird thing is, if I build it manually with `gcc nul1fs.c -lfuse -o nul1fs` it works!

Hah! After tinkering about for some time I've found the cause: for some reason `make` used different compiling method.
Also, apparently `LDFLAGS` is used for different purpose, you should have used `LDLIBS`
Here's the fix, add these two lines:
```
CC=gcc
LDLIBS="-lfuse"
```

System is `Linux namo 3.5.0-41-generic #64~precise1-Ubuntu SMP Thu Sep 12 16:50:04 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by xrgtn** [comment]
Hello,

On Wed, Jan 27, 2016 at 10:08:52AM -0800, Genda1ph
wrote:

> cc   "-lfuse"  nul1fs.c   -o nul1fs
> /tmp/ccT8jfGL.o: In function `main':
> nul1fs.c:(.text+0x4ae): undefined reference to`fuse_main_real'
> collect2: ld returned 1 exit status
> make: **\* [nul1fs] Error 1
> 
> ```
> Weird thing is, if I build it manually with `gcc
> nul1fs.c -lfuse -o nul1fs` it works!
> ```

Looks like there are 2 differences:
1. reverse order of "nul1fs.c" and "-lfuse" in the
   above 2 examples - it may indeed affect a linker
   (I saw it several times with "ld" and "-lc")
2. "cc" vs "gcc" (maybe your cc is symliked to
   clang instead of gcc)

> Also, apparently `LDFLAGS` is used for different
> purpose, you should have used `LDLIBS`

Thanks, you are right! I've changed LDFLAGS to
LDLIBS, this should solve the incorrect order
problem.

> CC=gcc

Regarding this I'm not sure. I think nullfs should
build just fine with clamg too.

## 

WBR,
xrgtn

**Comment by Genda1ph** [comment]
There's only GCC (no Clang)
I've managed to reproduce the error:

```
gendalph@namo:~/nullfs-master$ cc -lfuse nul1fs.c -o nul1fs
/tmp/ccRNV6di.o: In function `main':
nul1fs.c:(.text+0x4ae): undefined reference to `fuse_main_real'
collect2: ld returned 1 exit status
```

However, two other calls produced a working binary:

```
gendalph@namo:~/nullfs-master$ cc nul1fs.c -lfuse -o nul1fs
gendalph@namo:~/nullfs-master$ cc nul1fs.c -o nul1fs -lfuse
```

So, this is indeed an issue of arguments' position.
Now we just need to figure out why this occurs.

**Comment by Genda1ph** [comment]
As for Clang, I've just compiled `nul1fs`, `nullfs` and `nullnfs` on ArchLinux with Clang (`clang version 3.7.1 (tags/RELEASE_371/final)`), but haven't tried them.

`nulnfs` threw a bunch of warnings during compilation:

```
clang nulnfs.c -lfuse -o nulnfs.c
nulnfs.c:118:52: warning: format specifies type 'int' but the argument has type '__off64_t' (aka 'long') [-Wformat]
            name, (int)(dirent - all_dirents + 1), dirent->de.d_off);
                                                   ^~~~~~~~~~~~~~~~
nulnfs.c:224:9: warning: format specifies type 'int' but the argument has type 'fuse_ino_t' (aka 'unsigned long') [-Wformat]
        ino, &dinode->ls_ent);
        ^~~
nulnfs.c:245:25: warning: implicit declaration of function 'fuse_dirent_size' is invalid in C99 [-Wimplicit-function-declaration]
        size_t e_size = fuse_dirent_size(strlen(dirent->de.d_name));
                        ^
nulnfs.c:284:31: warning: format specifies type 'unsigned int' but the argument has type 'uint64_t' (aka 'unsigned long') [-Wformat]
        (int) ino, (int) off, fi->fh, (unsigned) size);
                              ^~~~~~
```

Otherwise everything seems fine.

**Comment by xrgtn** [comment]
Hello,

On Thu, Jan 28, 2016 at 06:58:29AM -0800, Genda1ph
wrote:

> `nulnfs` threw a bunch of warnings during compilation:
> 
> ```
> clang nulnfs.c -lfuse -o nulnfs.c
> nulnfs.c:118:52: warning: format specifies type 'int' but the argument has type '__off64_t' (aka 'long') [-Wformat]
>             name, (int)(dirent - all_dirents + 1), dirent->de.d_off);
> ```

This is because nulnfs implementation is still
broken (nul1fs and nullfs are OK), and 64bit
compilation shows some screwage WRT offsets.

## 

WBR,
xrgtn

**Comment by xrgtn** [comment]
On Thu, Jan 28, 2016 at 06:40:04AM -0800, Genda1ph
wrote:

> So, this is indeed an issue of arguments' position.

Order of object files and libraries is important
for linker. You have correctly indicated that -lXXX
options must be put into LDLIBS, not LDFLAGS,
otherwise -lXXX libraries will be put _before_
object files in an 'ld' invocation, like that:

  cc $(LDFLAGS) <objs> $(LDLIBS) -o <output>

Citing `info make "Catalogue of Rules"`:

> Linking a single object file
>      'N' is made automatically from 'N.o' by running the linker (usually
>      called 'ld') via the C compiler.  The precise recipe used is
>      '$(CC) $(LDFLAGS) N.o $(LOADLIBES) $(LDLIBS)'.

By the way, if you'd like to use ld directly
instead of cc/gcc, you will need to put prologue
and epilogue object files around your objects in
correct order:

ld $(LDFLAGS) crt1.o crti.o crtbegin.o <objs> crtend.o crtn.o $(LDLIBS) -o <output>

Here's some explanation of what crtXXX.o objects
do:
http://wiki.osdev.org/Creating_a_C_Library#crtbegin.o.2C_crtend.o.2C_crti.o.2C_and_crtn.o

> Now we just need to figure out why this occurs.

It's just my fault -- I didn't remember that "-l"
options must be put in LDLIBS instead of LDFLAGS.
Thanks again for pointing that.

## 

WBR,
xrgtn

**Comment by xrgtn** [comment]
> Here's some explanation of what crtXXX.o objects
> do:
> http://wiki.osdev.org/Creating_a_C_Library#crtbegin.o.2C_crtend.o.2C_crti.o.2C_and_crtn.o
> 
> The idea is that files are linked in this order:
> crt0.o, crti.o, crtbegin.o, your-program-foo.o,
> your-program-bar.o, crtend.o, crtn.o

On current systems there's no crt0.o anymore and
crt1.o is used instead.

On my Debian system crt{1,i,n}.o live in the
/usr/lib/x86_64-linux-gnu/ directory and
crtbegin.o and crtend.o -- in
/usr/lib/gcc/x86_64-linux-gnu/5/.

P.S. Also, ld without -dynamic-linker produces
wrong ld.so dependency on Debian (/lib/ld64.so.1),
therefore if you want to use 'ld' instead of 'cc',
you will need to explicitly specify
-dynamic-linker. Summarily this would look like
that:

ld -o hello /usr/lib/x86_64-linux-gnu/crt1.o \
  /usr/lib/x86_64-linux-gnu/crti.o \
  /usr/lib/gcc/x86_64-linux-gnu/5/crtbegin.o \
  hello.o \
  /usr/lib/gcc/x86_64-linux-gnu/5/crtend.o \
  /usr/lib/x86_64-linux-gnu/crtn.o \
  -lc \
  -dynamic-linker /lib64/ld-linux-x86-64.so.2

## 

WBR,
xrgtn

**Comment by Genda1ph** [comment]
Anyway, we should probably close this issue, maybe put a note somewhere on compiling it on Ubuntu 12, though it'll soon become obsolete.

**Comment by xrgtn** [comment]
Moving "-lfuse" from LDFLAGS to LDLIBS should fix compiling on Ubuntu 12 too, I beleive. Closing the issue via github web interface (I didn't even know I'm supposed to or should close github issues at all).
Thanks for your report.
